
language: cpp
os: osx
compiler: clang

before_install:
  - brew update
  - brew tap homebrew/science
  - brew update
  - brew install cmake adol-c

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./auto_vs_finite

