
language: cpp
os: osx

before_install:
  - brew update
  - brew tap homebrew/science
  - brew update
  - brew install adol-c

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./auto_vs_finite

